package com.santimaszong.Sistema_de_Gestion_de_Programas.domain.enums;

public enum Departamento {
    AGRONOMIA,
    BIOLOGIA_BIOQUIMICA_Y_FARMACIA,
    CIENCIAS_DE_LA_ADMINISTRACION,
    CIENCIAS_DE_LA_EDUCACION,
    CIENCIAS_DE_LA_SALUD,
    CIENCIAS_E_INGENIERIA_DE_LA_COMPUTACION,
    DERECHO,
    ECONOMIA,
    FISICA,
    GEOGRAFIA_Y_TURISMO,
    GEOLOGIA,
    HUMANIDADES,
    INGENIERIA,
    INGENIERIA_ELECTRICA_Y_DE_COMPUTADORAS,
    INGENIERIA_QUIMICA,
    MATEMATICA,
    QUIMICA
}