spring.application.name=Sistema_de_Gestion_de_Programas
server.port=${SERVER_PORT}

# DB (desde variables de entorno)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS
app.allowed-origins=http://localhost:3000,https://sistema-de-gestion-de-programas-fro.vercel.app

# JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=86400000
security.jwt.refresh-expiration-ms=604800000
server.servlet.session.cookie.secure=true


# PDF
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8


# Email
spring.mail.host=smtp.gmail.com
#spring.mail.port=587
spring.mail.port=465
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

# Propiedades de protocolo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
