spring.application.name=Sistema_de_Gestion_de_Programas


spring.datasource.url=jdbc:postgresql://pg-sgp25-sistema-de-gestion-de-programas.b.aivencloud.com:18549/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_8Sg9XbhenAVT1GYIfrK
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.allowed-origins=http://localhost:3000`

security.jwt.secret=ReplaceThisWithASecureKeyOfAtLeast32Chars12345
security.jwt.expiration-ms=900000              # 15min
security.jwt.refresh-expiration-ms=604800000    # 7 días
server.servlet.session.cookie.secure=true



#spring.application.name=Sistema_de_Gestion_de_Programas
#
## DB (desde variables de entorno)
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## CORS
#app.allowed-origins=http://localhost:3000
#
## JWT
#security.jwt.secret=ReplaceThisWithASecureKeyOfAtLeast32Chars12345
#security.jwt.expiration-ms=900000              # 15min
#security.jwt.refresh-expiration-ms=604800000    # 7 días
#
#server.servlet.session.cookie.secure=true
#
#server.port=${PORT:8080}
