spring.application.name=Sistema_de_Gestion_de_Programas

spring.datasource.url=jdbc:postgresql://pg-sgp25-sistema-de-gestion-de-programas.b.aivencloud.com:18549/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_8Sg9XbhenAVT1GYIfrK
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
